# See https://pre-commit.com for more information.
# Run against all files: `uv run pre-commit run --all-files`.
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: taplo
        name: taplo
        entry: uv run taplo fmt --check
        language: system
        types: [toml]
      - id: yamlfix
        name: yamlfix
        entry: uv run yamlfix --check
        language: system
        types: [yaml]
      - id: mdformat
        name: mdformat
        entry: uv run mdformat --check
        language: system
        types: [markdown]
      - id: codespell
        name: codespell
        entry: uv run codespell
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: uv run mypy src tests
        language: system
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: uv run pytest --cov --cov-report=term-missing
        language: system
        types: [python]
        pass_filenames: false
